"""
Django settings for agroguard project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# ==========================
# BASE DIRECTORY
# ==========================
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# SECURITY SETTINGS
# ==========================
SECRET_KEY = 'django-insecure-s_dpw(p!ee)fl9n0j_s9)#_n2xk*b2h!@gqpl9gy9z@z4ver03'

DEBUG = True

ALLOWED_HOSTS = []


# ==========================
# INSTALLED APPS
# ==========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps lokal kamu
    'dashboard',
    'accounts',
]


# ==========================
# MIDDLEWARE
# ==========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================
# URL & WSGI
# ==========================
ROOT_URLCONF = 'agroguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agroguard.wsgi.application'


# ==========================
# DATABASE
# ==========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==========================
# PASSWORD VALIDATORS
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================
# INTERNATIONALIZATION
# ==========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================
# STATIC & MEDIA FILES
# ==========================

# URL prefix for static files
STATIC_URL = '/static/'

# Folder tempat Django mencari file statis
STATICFILES_DIRS = [
    BASE_DIR / "static",                      # folder static utama proyek
    BASE_DIR / "accounts" / "static",         # folder static milik app accounts
    BASE_DIR / "dashboard" / "static",        # opsional
    BASE_DIR / "detection" / "static",        # opsional
    BASE_DIR / "recommendation" / "static",   # opsional
]

# Folder hasil collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (gambar upload, dsb.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================
# LOGIN / LOGOUT REDIRECTS
# ==========================
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "/login/"


# ==========================
# DEFAULT PRIMARY KEY
# ==========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
