"""
Django settings for agroguard project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# ==========================
# BASE DIRECTORY
# ==========================
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# SECURITY SETTINGS
# ==========================
SECRET_KEY = 'django-insecure-s_dpw(p!ee)fl9n0j_s9)#_n2xk*b2h!@gqpl9gy9z@z4ver03'

DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts (untuk development)


# ==========================
# INSTALLED APPS
# ==========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps - TAMBAHKAN INI! 
    'rest_framework',
    'corsheaders',

    # Apps lokal kamu
    'dashboard',
    'accounts',
    'admin_dashboard',

]


# ==========================
# MIDDLEWARE
# ==========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← TAMBAHKAN INI!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================
# URL & WSGI
# ==========================
ROOT_URLCONF = 'agroguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agroguard.wsgi.application'


# ==========================
# DATABASE
# ==========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agroguard_db',           # Nama database di phpMyAdmin
        'USER': 'root',                    # Username MySQL (biasanya 'root')
        'PASSWORD': '',                    # Password MySQL (kosongkan jika default XAMPP)
        'HOST': 'localhost',               # atau '127.0.0.1'
        'PORT': '3306',                    # Port MySQL default
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# ==========================
# PASSWORD VALIDATORS
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================
# INTERNATIONALIZATION
# ==========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================
# STATIC & MEDIA FILES
# ==========================

# URL prefix for static files
STATIC_URL = '/static/'

# Folder tempat Django mencari file statis
STATICFILES_DIRS = [
    BASE_DIR / "static",                      # folder static utama proyek
    BASE_DIR / "accounts" / "static",         # folder static milik app accounts
]

# Folder hasil collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (gambar upload, dsb.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================
# LOGIN / LOGOUT REDIRECTS
# ==========================
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "/login/"


# ==========================
# DEFAULT PRIMARY KEY
# ==========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

# ==========================
# LOGIN / LOGOUT REDIRECTS
# ==========================
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'dashboard:home'  # Default redirect setelah login
LOGOUT_REDIRECT_URL = 'accounts:login'

# ===================================
# CORS Configuration (untuk ESP8266)
# ===================================
CORS_ALLOW_ALL_ORIGINS = True  # Allow all untuk testing

# ===================================
# REST Framework Configuration
# ===================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow ESP8266 tanpa login
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}