# Generated by Django 5.2.8 on 2025-12-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_alter_admin_divisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitraDaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('path_file', models.ImageField(upload_to='citra_daun/%Y/%m/%d/')),
                ('jenis_tanaman', models.CharField(blank=True, max_length=100, verbose_name='Jenis Tanaman')),
                ('status_deteksi', models.CharField(choices=[('pending', 'Menunggu Deteksi'), ('processing', 'Sedang Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('waktu_upload', models.DateTimeField(auto_now_add=True)),
                ('waktu_deteksi', models.DateTimeField(blank=True, null=True)),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citra_upload', to='accounts.petani')),
            ],
            options={
                'verbose_name': 'Citra Daun',
                'verbose_name_plural': 'Citra Daun',
                'db_table': 'citra_daun',
                'ordering': ['-waktu_upload'],
            },
        ),
        migrations.CreateModel(
            name='JenisHama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Hama')),
                ('nama_latin', models.CharField(blank=True, max_length=150, verbose_name='Nama Latin')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hama/', verbose_name='Gambar Hama')),
                ('gejala', models.TextField(blank=True, verbose_name='Gejala Serangan')),
                ('cara_pencegahan', models.TextField(blank=True, verbose_name='Cara Pencegahan')),
                ('cara_penanganan', models.TextField(blank=True, verbose_name='Cara Penanganan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Hama',
                'verbose_name_plural': 'Jenis Hama',
                'db_table': 'jenis_hama',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='HasilDeteksi',
            fields=[
                ('citra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hasil_deteksi', serialize=False, to='dashboard.citradaun')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tingkat_serangan', models.CharField(blank=True, choices=[('ringan', 'Ringan'), ('sedang', 'Sedang'), ('berat', 'Berat')], max_length=10, null=True)),
                ('jumlah_daun_terinfeksi', models.IntegerField(default=1)),
                ('koordinat_bbox', models.JSONField(blank=True, null=True)),
                ('gambar_hasil', models.ImageField(blank=True, null=True, upload_to='hasil_deteksi/%Y/%m/%d/')),
                ('rekomendasi', models.TextField(blank=True, verbose_name='Rekomendasi Penanganan')),
                ('waktu_deteksi', models.DateTimeField(auto_now_add=True)),
                ('jenis_hama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteksi_hama', to='dashboard.jenishama')),
            ],
            options={
                'verbose_name': 'Hasil Deteksi',
                'verbose_name_plural': 'Hasil Deteksi',
                'db_table': 'hasil_deteksi',
            },
        ),
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(max_length=100, verbose_name='Nama Unit')),
                ('lokasi', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('luas_daerah', models.CharField(max_length=50, verbose_name='Luas Daerah')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('foto_unit', models.ImageField(blank=True, null=True, upload_to='lahan/', verbose_name='Foto Unit Monitoring')),
                ('jenis_tanaman', models.CharField(default='Padi', max_length=100, verbose_name='Jenis Tanaman')),
                ('status_aktif', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lahan_milik', to='accounts.petani')),
            ],
            options={
                'verbose_name': 'Lahan/Unit Monitoring',
                'verbose_name_plural': 'Lahan/Unit Monitoring',
                'db_table': 'lahan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='citradaun',
            name='lahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citra_lahan', to='dashboard.lahan'),
        ),
        migrations.CreateModel(
            name='RiwayatDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan_petani', models.TextField(blank=True, verbose_name='Catatan')),
                ('status_penanganan', models.CharField(choices=[('belum', 'Belum Ditangani'), ('proses', 'Sedang Ditangani'), ('selesai', 'Sudah Selesai')], default='belum', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lahan')),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_deteksi', to='accounts.petani')),
                ('hasil_deteksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='dashboard.hasildeteksi')),
            ],
            options={
                'verbose_name': 'Riwayat Deteksi',
                'verbose_name_plural': 'Riwayat Deteksi',
                'db_table': 'riwayat_deteksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ESP8266_001', help_text='ID unik ESP8266', max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Suhu dalam Celsius (°C)', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Kelembapan udara dalam persen (%)', max_digits=5)),
                ('soil_moisture', models.IntegerField(default=0, help_text='Kelembapan tanah dalam persen (0-100%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Waktu data diterima')),
                ('lahan', models.ForeignKey(blank=True, help_text='Lahan yang dimonitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='dashboard.lahan')),
                ('petani', models.ForeignKey(blank=True, help_text='Petani pemilik sensor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='accounts.petani')),
            ],
            options={
                'verbose_name': 'Data Sensor',
                'verbose_name_plural': 'Data Sensor',
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx'), models.Index(fields=['device_id', '-timestamp'], name='sensor_data_device__aa8879_idx')],
            },
        ),
    ]
