# Generated by Django 5.2.6 on 2025-10-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PencegahanHama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_hama', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=200)),
                ('sumber', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
