# Generated by Django 5.2.7 on 2025-11-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ESP8266_001', help_text='ID unik ESP8266', max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Suhu dalam Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Kelembapan dalam persen', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Waktu data diterima')),
                ('lahan', models.ForeignKey(blank=True, help_text='Lahan yang dimonitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='dashboard.lahan')),
                ('petani', models.ForeignKey(blank=True, help_text='Petani pemilik sensor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='accounts.petani')),
            ],
            options={
                'verbose_name': 'Data Sensor',
                'verbose_name_plural': 'Data Sensor',
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
