# Generated by Django 4.2.26 on 2025-12-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatdeteksi',
            name='petani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='accounts.petani'),
        ),
    ]
