# Generated by Django 4.2.26 on 2025-12-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=150)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='detections/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_1', models.TextField()),
                ('pesticide_2', models.TextField()),
                ('pesticide_3', models.TextField()),
                ('organic_alternative', models.TextField()),
                ('dosage', models.CharField(max_length=50)),
                ('spray_volume', models.CharField(max_length=50)),
                ('application_time', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=50)),
                ('waiting_period', models.CharField(max_length=50)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='dashboard.detectionresult')),
            ],
        ),
    ]
