# Generated by Django 4.2.26 on 2025-12-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_riwayatdeteksi_petani'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.IntegerField(default=0, help_text='Kelembapan tanah dalam persen (0-100%)'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, help_text='Kelembapan udara dalam persen (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text='Suhu dalam Celsius (°C)', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device_id', '-timestamp'], name='sensor_data_device__aa8879_idx'),
        ),
    ]
