# Generated by Django 5.2.8 on 2025-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='divisi',
            field=models.CharField(blank=True, default='IT', max_length=50),
        ),
    ]
