# Generated by Django 5.2.7 on 2025-11-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisHama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Hama')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hama/', verbose_name='Gambar Hama')),
                ('jumlah_serangan', models.IntegerField(default=0, verbose_name='Jumlah Serangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Hama',
                'verbose_name_plural': 'Jenis Hama',
                'db_table': 'admin_jenis_hama',
                'ordering': ['-jumlah_serangan'],
            },
        ),
        migrations.CreateModel(
            name='StatistikHama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('tingkat', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, verbose_name='Tingkat')),
                ('jumlah', models.IntegerField(verbose_name='Jumlah Kasus')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistik Hama',
                'verbose_name_plural': 'Statistik Hama',
                'db_table': 'statistik_hama',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='PencegahanHama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('sumber', models.URLField(max_length=500, verbose_name='Sumber')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Lengkap')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('pending', 'Pending'), ('selesai', 'Selesai')], default='aktif', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jenis_hama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pencegahan_hama', to='admin_dashboard.jenishama', verbose_name='Jenis Hama')),
            ],
            options={
                'verbose_name': 'Pencegahan Hama',
                'verbose_name_plural': 'Pencegahan Hama',
                'db_table': 'pencegahan_hama',
                'ordering': ['-created_at'],
            },
        ),
    ]
