# Generated by Django 5.2.7 on 2025-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenishama',
            name='gejala',
            field=models.TextField(blank=True, null=True, verbose_name='Gejala Serangan'),
        ),
        migrations.AddField(
            model_name='jenishama',
            name='nama_latin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Latin'),
        ),
    ]
