# Generated by Django 5.2.9 on 2025-12-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('plant_name', models.CharField(max_length=100)),
                ('pest_name', models.CharField(max_length=100)),
                ('severity_level', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_path', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosageInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('spray_volume', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('interval_days', models.IntegerField()),
                ('pre_harvest_interval', models.IntegerField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroguard_app.detectionresult')),
            ],
        ),
        migrations.CreateModel(
            name='FilesResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=255)),
                ('youtube_url', models.CharField(max_length=255)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroguard_app.detectionresult')),
            ],
        ),
        migrations.CreateModel(
            name='PesticideRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroguard_app.detectionresult')),
            ],
        ),
        migrations.CreateModel(
            name='PestTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroguard_app.detectionresult')),
            ],
        ),
    ]
