# Generated by Django 5.2.7 on 2025-10-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_migrate_users_to_isa'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(max_length=100)),
                ('lokasi', models.TextField()),
                ('luas_daerah', models.DecimalField(decimal_places=2, help_text='Luas dalam hektar', max_digits=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('petani', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lahan_milik', to='accounts.petani')),
            ],
            options={
                'verbose_name': 'Lahan',
                'verbose_name_plural': 'Lahan',
                'db_table': 'lahan',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.DeleteModel(
            name='PencegahanHama',
        ),
    ]
